[platformio]
default_envs = esp32-s3-super-mini

[env:esp32-s3-super-mini]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/rei-vilo/PDLS_EXT3_Basic_Global.git#8.2.0
build_flags =
    -DCORE_DEBUG_LEVEL=1
build_src_filter =
    +<*>
    -<server_epaper_test.cpp>

[env:epaper-server-test]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/rei-vilo/PDLS_EXT3_Basic_Global.git#8.2.0
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DEPD_SERVER_TEST
build_src_filter =
    +<server_epaper_test.cpp>
    +<epd_format.cpp>
    -<main.cpp>

[env:native]
platform = native
test_build_src = yes
build_src_filter =
    +<epd_format.cpp>
    -<main.cpp>
