#pragma once

// Copy this file to include/secrets.h and replace the placeholders.
// include/secrets.h is ignored by Git.

#define WIFI_SSID "YOUR_WIFI_NAME"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

// Public GitHub Pages URL generated by the bot.
#define EPD_IMAGE_URL "https://YOUR_USER.github.io/YOUR_REPOSITORY/private-path/current.epd"

