#pragma once

// Copy this file to include/secrets.h and replace the placeholders.
// include/secrets.h is ignored by Git.

#define WIFI_SSID "YOUR_WIFI_NAME"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

// Public GitHub Pages URL generated by the bot.
#define EPD_IMAGE_URL "https://xxrochetxx.github.io/ESPSUPERMINI/display/22a7a15a92a99aae4446f9d62b5f57dd/current.epd"
